export const ANSWERS = [
  'about', 'above', 'actor', 'acute', 'adopt', 'adult', 'after', 'again', 'agent', 'agree',
  'ahead', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone', 'along', 'amber',
  'angel', 'anger', 'angle', 'apple', 'apply', 'arena', 'argue', 'arise', 'aside', 'audio',
  'avoid', 'award', 'aware', 'bacon', 'badge', 'baker', 'basic', 'beach', 'beard', 'begin',
  'being', 'below', 'bench', 'berry', 'birth', 'black', 'blade', 'blame', 'blank', 'blast',
  'blend', 'blind', 'block', 'bloom', 'board', 'boost', 'brain', 'brave', 'bread', 'break',
  'brick', 'brief', 'bring', 'broad', 'brown', 'brush', 'build', 'bunch', 'cabin', 'candy',
  'cargo', 'carry', 'catch', 'cause', 'chain', 'chair', 'chalk', 'charm', 'chart', 'chase',
  'cheap', 'check', 'chess', 'chest', 'chief', 'child', 'civic', 'claim', 'class', 'clean',
  'clear', 'climb', 'clock', 'close', 'cloud', 'coach', 'coast', 'coral', 'count', 'court',
  'cover', 'craft', 'crane', 'crash', 'cream', 'crisp', 'crowd', 'crown', 'curve', 'cycle',
  'daily', 'dance', 'delta', 'depth', 'diary', 'dough', 'draft', 'drama', 'dream', 'dress',
  'drift', 'drink', 'drive', 'eager', 'eagle', 'early', 'earth', 'eight', 'elbow', 'elder',
  'empty', 'enjoy', 'enter', 'equal', 'event', 'exact', 'extra', 'fable', 'faith', 'false',
  'feast', 'fence', 'fever', 'field', 'flame', 'flash', 'fleet', 'float', 'flock', 'floor',
  'flour', 'focus', 'force', 'forge', 'frame', 'fresh', 'front', 'frost', 'fruit', 'funny',
  'ghost', 'giant', 'given', 'glass', 'globe', 'glory', 'grace', 'grain', 'grand', 'grape',
  'grass', 'great', 'green', 'grind', 'group', 'guard', 'guess', 'guide', 'habit', 'happy',
  'harsh', 'heart', 'heavy', 'hello', 'honey', 'horse', 'hotel', 'house', 'human', 'humor',
  'ideal', 'image', 'index', 'inner', 'input', 'issue', 'ivory', 'jelly', 'jewel', 'joint',
  'judge', 'juice', 'knife', 'knock', 'label', 'laser', 'later', 'laugh', 'layer', 'learn',
  'lemon', 'level', 'light', 'limit', 'linen', 'local', 'logic', 'loose', 'lucky', 'lunar',
  'magic', 'major', 'maple', 'march', 'match', 'mayor', 'medal', 'metal', 'minor', 'model',
  'money', 'month', 'moral', 'mount', 'mouse', 'mouth', 'movie', 'music', 'nerve', 'never',
  'night', 'noble', 'noise', 'north', 'novel', 'nurse', 'ocean', 'offer', 'olive', 'onion',
  'opera', 'orbit', 'order', 'other', 'outer', 'owner', 'paint', 'panel', 'paper', 'party',
  'peace', 'peach', 'pearl', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pitch',
  'pizza', 'place', 'plain', 'plane', 'plant', 'plate', 'plaza', 'point', 'polar', 'pound',
  'power', 'press', 'price', 'pride', 'prime', 'print', 'prize', 'proof', 'proud', 'pulse',
  'quick', 'quiet', 'quilt', 'quote', 'radar', 'radio', 'raise', 'range', 'rapid', 'ratio',
  'reach', 'ready', 'realm', 'relax', 'reply', 'rider', 'ridge', 'right', 'river', 'robin',
  'robot', 'rocky', 'round', 'route', 'royal', 'rural', 'salad', 'sauce', 'scale', 'scene',
  'scope', 'score', 'scout', 'sense', 'serve', 'seven', 'shade', 'shake', 'shape', 'share',
  'sharp', 'sheep', 'shelf', 'shell', 'shift', 'shine', 'shirt', 'shock', 'shore', 'short',
  'sight', 'skill', 'slate', 'sleep', 'slice', 'slide', 'small', 'smart', 'smile', 'smoke',
  'snake', 'solar', 'solid', 'solve', 'sound', 'south', 'space', 'spare', 'spark', 'speak',
  'speed', 'spend', 'spice', 'spike', 'spine', 'spoon', 'sport', 'squad', 'stack', 'staff',
  'stage', 'stair', 'stamp', 'stand', 'start', 'state', 'steam', 'steel', 'stick', 'stone',
  'storm', 'story', 'stove', 'strip', 'study', 'style', 'sugar', 'suite', 'sunny', 'super',
  'sweet', 'swift', 'table', 'taste', 'teach', 'thank', 'theme', 'thick', 'thing', 'think',
  'thumb', 'tiger', 'title', 'toast', 'topic', 'torch', 'total', 'touch', 'tower', 'trace',
  'track', 'trade', 'trail', 'train', 'treat', 'trend', 'trial', 'tribe', 'trick', 'truck',
  'trust', 'truth', 'twist', 'uncle', 'under', 'union', 'unity', 'upper', 'urban', 'usual',
  'valid', 'value', 'vapor', 'vault', 'video', 'vigor', 'vital', 'vivid', 'vocal', 'voice',
  'water', 'whale', 'wheat', 'wheel', 'white', 'whole', 'woman', 'world', 'worth', 'wound',
  'wrist', 'write', 'yacht', 'young', 'youth', 'zebra', 'clamp', 'boxed', 'hoped', 'sighs',
  'heard', 'rants', 'topaz', 'focus', 'fawns', 'attic', 'whirl', 'taxes', 'sigma', 'biped',
  'nomad', 'thuds', 'divas', 'motto', 'annal', 'envoy', 'shred', 'gouge', 'jokes', 'dines',
  'seize', 'spore', 'jeeps', 'rated', 'snipe', 'palms', 'arrow', 'hinds', 'essay', 'brows',
  'scarf', 'strum', 'sheer', 'ashes', 'legal', 'trout', 'waned', 'media', 'fleet', 'event',
  'briar', 'weave', 'vapid', 'yolks', 'askew', 'stymy', 'plank', 'blurt', 'truce', 'folks',
  'mercy', 'funky', 'eight', 'shyly', 'class', 'culls', 'bites', 'ranks', 'steps', 'acids',
  'salon', 'froze', 'curls', 'warts', 'teens', 'chick', 'peace', 'wispy', 'weigh', 'coupe',
  'pelts', 'doors', 'input', 'gross', 'areas', 'ships', 'clots', 'rouge', 'fiber', 'stink',
  'altar', 'ferry', 'canon', 'monks', 'ochre', 'extol', 'shool', 'gawks', 'flaws', 'ocean',
  'verbs', 'klutz', 'chive', 'savor', 'ninth', 'cabin', 'crown', 'label', 'gored', 'ponds',
  'shows', 'kempt', 'fuzzy', 'inlet', 'fears', 'await', 'begar', 'cease', 'ebony', 'break',
  'guild', 'kings', 'lions', 'giver', 'gamer', 'gazer', 'refer', 'swipe', 'coups', 'pique',
  'shack', 'these', 'stave', 'soggy', 'awful', 'smile', 'clods', 'beaus', 'agile', 'hobos',
  'loans', 'poker', 'sages', 'blobs', 'weeps', 'biked', 'glens', 'bling', 'aorta', 'gunks',
  'loner', 'defer', 'hypes', 'brink', 'lemur', 'tidal', 'tufts', 'dream', 'pains', 'lakes',
  'pings', 'elude', 'rotes', 'often', 'cacti', 'dined', 'cocoa', 'easel', 'fully', 'trope',
  'acute', 'blunt', 'pupil', 'birth', 'pints', 'clove', 'stump', 'baked', 'clans', 'stole',
  'spray', 'risky', 'vasal', 'catch', 'tango', 'sigil', 'ruler', 'upend', 'unfit', 'aught',
  'beans', 'clean', 'tanks', 'reply', 'hived', 'fuels', 'fired', 'rinse', 'blink', 'sorry',
  'black', 'odors', 'beaut', 'bulky', 'pores', 'holds', 'cream', 'track', 'duvet', 'heals',
  'drool', 'topic', 'slams', 'grins', 'jumps', 'nuked', 'belay', 'skirt', 'plots', 'rooms',
  'chase', 'eater', 'slate', 'cushy', 'obese', 'spine', 'grime', 'parry', 'loves', 'cited',
  'mulls', 'slows', 'smash', 'dents', 'chair', 'badge', 'glyph', 'poets', 'valor', 'widen',
  'shame', 'knack', 'grave', 'puffs', 'geeky', 'blush', 'evens', 'rhyme', 'teeny', 'hitch',
  'corny', 'slyly', 'layer', 'jumbo', 'mangy', 'ghost', 'gassy', 'tract', 'enter', 'pygmy',
  'wagon', 'salty', 'sixes', 'lousy', 'daunt', 'cults', 'sadly', 'loops', 'bumpy', 'comet',
  'quads', 'yikes', 'trite', 'leapt', 'acted', 'lasso', 'ovals', 'emoji', 'pixel', 'tints',
  'eject', 'keels', 'joins', 'ionic', 'print', 'witch', 'wiped', 'burns', 'swoon', 'bugle',
  'stabs', 'genre', 'annul', 'nerve', 'baths', 'icier', 'reams', 'rangs', 'stunk', 'squid',
  'infer', 'teeth', 'brews', 'creek', 'chops', 'fills', 'sixth', 'queue', 'scoop', 'sorts',
  'twirl', 'eerie', 'aging', 'gummy', 'serum', 'boils', 'realm', 'stuns', 'soles', 'frame',
  'visit', 'cabal', 'ridge', 'sling', 'aware', 'mucus', 'grail', 'stead', 'zones', 'soapy',
  'gazed', 'block', 'pride', 'melds', 'rodeo', 'above', 'spuds', 'tutus', 'blood', 'idyll',
  'gives', 'tuffs', 'named', 'coral', 'wench', 'cubed', 'lamer', 'imbue', 'hurts', 'cloak',
  'cubic', 'riled', 'unbox', 'orcas', 'slick', 'maims', '
]

export function randomAnswers(count: number) {
  const pool = [...ANSWERS]
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[pool[i], pool[j]] = [pool[j], pool[i]]
  }
  return pool.slice(0, count)
}

export function randomAnswer() {
  return ANSWERS[Math.floor(Math.random() * ANSWERS.length)]
}
